---
# BATT1, READ, CMD
# BATT1, WRITE, CMD=Value
BATT1: 
   Description: BATTERY CHARGER
   CAN:
      Speed: 500000 
      Port: can0
   Interval: 5000
   Neighbors: []
   VoltageRegulateDG: 1
   debugMode: False

   Events:
      BatteryVoltage:
   Polled:
      BatteryTemperature:

###### READ/WRITE Commands - Holding registers #######
   BatteryVoltage:
      info: Read battery voltage
      ID: 0x043
      ADDRTYPE: Standard   # May be 'Standard' or 'Extended'
      MSGTYPE: Event       # May be 'Event' or 'Polled'
      DLEN: 6              # Total length of the data being sent or received
      output_value: 0
      data_format: ">H"    # data format ">" is big endian, "<" is little endian. f-float
      Units:
         - 1               # scaling factor 
         - Volts           # units for data value

   BatteryTemperature:
      info: Read battery temperature
      ID: 0x044
      ADDRTYPE: Standard   # May be 'Standard' or 'Extended'
      MSGTYPE: Polled      # May be 'Event' or 'Polled'
      DLEN: 6              # Total length of the data being sent or received
      output_value: 0
      data_format: ">H"    # data format ">" is big endian, "<" is little endian. f-float
      Units:
         - 1               # scaling factor 
         - Celcius         # units for data value


